change

diff --git a/10-loops-sh b/10-loops-sh
--- a/10-loops-sh
+++ b/10-loops-sh
@@ -1,6 +1,27 @@
 #!/bin/bash
 
-for i in {1..100}
+USERID=$(id -u)
+LOGS_FOLDER="/var/log/Shell-scriptpractice"
+LOGS_FILE="/var/log/Shell-scriptpractice/$0.log"
+
+if [ $USERID -ne 0 ]; then
+    echo "Please run with sudo access" | tee -a $LOGS_FILE
+    exit 1 
+fi
+
+mkdir -p $LOGS_FOLDER
+##Function name ###
+VALIDATE(){
+if [ $1 -ne 0 ]; then
+    echo "$2....failure" | tee -a $LOGS_FILE
+    exit 1 
+else
+echo "$2...Success" | tee -a $LOGS_FILE
+fi
+}
+
+for package in $@
 do
-  echo $i
+    dnf install $package-y
+    VALIDATE $? "$package Installation"
 done
